language: c #NOTE: this will set CC=gcc which might cause trouble
before_script:
  ## Install mainline msp430 toolchain for all build types
  - "sudo apt-get -qq update && sudo apt-get -qq install gcc-msp430 || true"
  ## Install toolchain for mc1233x in care-free way
  - "[ $BUILD_TYPE = multi ] && curl -s \
       https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2008q3-66-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 \
         | tar xjf - -C /tmp/ && sudo cp -f -r /tmp/arm-2008q3/* /usr/ && rm -rf /tmp/arm-2008q3 && arm-none-eabi-gcc --version || true"

script:
  ## The makefile called `.travis.mk` handles most of generic logic
  - "make -f .travis.mk $MAKE_TARGETS"

after_script:
  ## Print a basic summary in unix style
  - "echo 'Summary:'; cat results | sort | uniq -c"
  ## This will detect whether the build should pass or fail
  - "grep -v -q 'fail' results"


env:
  ## This magically kick-off parallel jobs for each of the for the sets
  ## of environment variable defined below
  - BUILD_TYPE='multi' MAKE_TARGETS='native minimal-net redbee-econotag sky'
